name: EasyFall
description: Disables Falling Damage (command-based)
version: 0.7.1 Beta
main: de.neptune_whitebear.EasyFall.EasyFall
softdepend: [Permissions]

commands:
    fallOn:
        description: Enable falling damage
        permission: easyfall.use
    fallOff:
        description: Disable falling damage
        permission: easyfall.use

permissions:
    easyfall.use:
        description: Allows usage of EasyFall
        default: op
